version: "3.9"
# 使用方式: 1.如果未初始化docker swarm，则执行docker swarm init, 然后执行 docker stack deploy webapi -c .\docker-compose.yml

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - C:/.docker-volume/redis:/data
    command: redis-server --save 120 1 --maxmemory 200m --requirepass passwd1234 --bind 0.0.0.0
    networks:
      - redis
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: passwd1234
    networks:
      - db
    ports:
      - target: 3306
        published: 3306
        mode: host
    volumes:
      - C:/.docker-volume/mysql:/var/lib/mysql

  # 管理mysql数据库,访问http://localhost:8080 host=db user=root password=passwd1234
  adminer:
    image: adminer
    restart: always
    ports:
      - target: 8080
        published: 8080
        mode: host
    networks:
      - db
    depends_on:
      - db
  
  # 管理redis数据库,访问http://localhost:8081
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: passwd1234
      PORT: 8081
    ports:
      - target: 8081
        published: 8081
        mode: host
    networks:
      - redis
    depends_on:
      - redis

networks:
  db:
  redis:
